In [1]:
# Import Modules
import numpy as np
import pandas as pd

**Import and clean zillow CSV and calculate average annual home price by neighborhood**

In [2]:
# Read in and View CSV
zillow_df = pd.read_csv("Resources/Neighborhood_zillow_real_estate_data.csv")
zillow_df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2000-01-31,...,2024-05-31,2024-06-30,2024-07-31,2024-08-31,2024-09-30,2024-10-31,2024-11-30,2024-12-31,2025-01-31,2025-02-28
0,112345,0,Maryvale,neighborhood,AZ,AZ,Phoenix,"Phoenix-Mesa-Chandler, AZ",Maricopa County,67583.518398,...,3.414316e+05,3.423949e+05,3.428074e+05,3.427356e+05,3.419887e+05,3.408405e+05,3.396659e+05,3.388768e+05,3.377961e+05,3.359831e+05
1,192689,1,Paradise,neighborhood,NV,NV,Las Vegas,"Las Vegas-Henderson-Paradise, NV",Clark County,131822.893122,...,3.811490e+05,3.835971e+05,3.857815e+05,3.874718e+05,3.887102e+05,3.896048e+05,3.907356e+05,3.922168e+05,3.934987e+05,3.939496e+05
2,270958,2,Upper West Side,neighborhood,NY,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",New York County,381660.874369,...,1.169479e+06,1.169561e+06,1.173572e+06,1.182601e+06,1.187323e+06,1.191276e+06,1.203791e+06,1.222023e+06,1.237589e+06,1.245587e+06
3,270957,3,Upper East Side,neighborhood,NY,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",New York County,624209.066407,...,1.161944e+06,1.160380e+06,1.162163e+06,1.168415e+06,1.171441e+06,1.173235e+06,1.184594e+06,1.201830e+06,1.216919e+06,1.222750e+06
4,118208,4,South Los Angeles,neighborhood,CA,CA,Los Angeles,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,130013.865244,...,6.633109e+05,6.635775e+05,6.661953e+05,6.714373e+05,6.780470e+05,6.834528e+05,6.871959e+05,6.899128e+05,6.883663e+05,6.834446e+05

In [3]:
# Pull only the data for Denver
denver_real_estate_neighborhood_df = zillow_df.query("City == 'Denver'")
denver_real_estate_neighborhood_df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2000-01-31,...,2024-05-31,2024-06-30,2024-07-31,2024-08-31,2024-09-30,2024-10-31,2024-11-30,2024-12-31,2025-01-31,2025-02-28
235,273809,243,Gateway - Green Valley Ranch,neighborhood,CO,CO,Denver,"Denver-Aurora-Lakewood, CO",Denver County,159100.744442,...,491760.579762,490858.062361,489745.958237,488726.750030,487995.892604,487302.918410,486903.731696,486630.545212,485837.941119,484004.684275
329,6018,348,Montbello,neighborhood,CO,CO,Denver,"Denver-Aurora-Lakewood, CO",Denver County,126411.509704,...,441051.882758,440704.584839,439855.248083,439006.425223,438219.703796,437274.333697,436726.770604,436244.288979,435538.427024,433816.969981
410,275564,432,Central Park,neighborhood,CO,CO,Denver,"Denver-Aurora-Lakewood, CO",Denver County,NaN,...,810438.023097,808244.803889,805155.863258,802598.736735,801195.640708,799657.640124,798600.457230,798423.875011,797461.775214,795133.205809
602,268671,634,Hampden,neighborhood,CO,CO,Denver,"Denver-Aurora-Lakewood, CO",Denver County,166128.053070,...,525244.032565,523673.717091,522134.523951,521460.718137,521413.062907,521744.191939,522074.783631,522563.712560,522277.831180,520475.767806
681,268662,715,Five Points,neighborhood,CO,CO,Denver,"Denver-Aurora-Lakewood, CO",Denver County,188674.759005,...,618676.421526,615327.394116,611031.871498,607721.730126,605831.104045,604129.703444,603280.732065,603091.967420,603290.808745,603176.667680

In [4]:
# Drop Columns not needed
denver_real_estate_neighborhood_df = denver_real_estate_neighborhood_df.drop(columns=["SizeRank", "RegionType", "StateName", "State", "Metro", "CountyName"], axis=1)
denver_real_estate_neighborhood_df.head()

,RegionID,RegionName,City,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,...,2024-05-31,2024-06-30,2024-07-31,2024-08-31,2024-09-30,2024-10-31,2024-11-30,2024-12-31,2025-01-31,2025-02-28
235,273809,Gateway - Green Valley Ranch,Denver,159100.744442,159765.325210,160535.294508,162451.362079,164505.655223,166766.520599,168759.025196,...,491760.579762,490858.062361,489745.958237,488726.750030,487995.892604,487302.918410,486903.731696,486630.545212,485837.941119,484004.684275
329,6018,Montbello,Denver,126411.509704,127119.793823,127826.964815,129558.027973,131420.965731,133511.706505,135523.103627,...,441051.882758,440704.584839,439855.248083,439006.425223,438219.703796,437274.333697,436726.770604,436244.288979,435538.427024,433816.969981
410,275564,Central Park,Denver,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,810438.023097,808244.803889,805155.863258,802598.736735,801195.640708,799657.640124,798600.457230,798423.875011,797461.775214,795133.205809
602,268671,Hampden,Denver,166128.053070,166995.838447,168043.302926,170454.810786,173004.765599,175590.495277,177909.646389,...,525244.032565,523673.717091,522134.523951,521460.718137,521413.062907,521744.191939,522074.783631,522563.712560,522277.831180,520475.767806
681,268662,Five Points,Denver,188674.759005,190474.159808,191852.746828,195655.380983,199917.399170,204490.844183,209338.902439,...,618676.421526,615327.394116,611031.871498,607721.730126,605831.104045,604129.703444,603280.732065,603091.967420,603290.808745,603176.667680

In [5]:
#Rename Region Name Column
denver_real_estate_neighborhood_df.rename(columns={"RegionName":"Neighborhood"}, inplace=True)
denver_real_estate_neighborhood_df.head()

,RegionID,Neighborhood,City,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,...,2024-05-31,2024-06-30,2024-07-31,2024-08-31,2024-09-30,2024-10-31,2024-11-30,2024-12-31,2025-01-31,2025-02-28
235,273809,Gateway - Green Valley Ranch,Denver,159100.744442,159765.325210,160535.294508,162451.362079,164505.655223,166766.520599,168759.025196,...,491760.579762,490858.062361,489745.958237,488726.750030,487995.892604,487302.918410,486903.731696,486630.545212,485837.941119,484004.684275
329,6018,Montbello,Denver,126411.509704,127119.793823,127826.964815,129558.027973,131420.965731,133511.706505,135523.103627,...,441051.882758,440704.584839,439855.248083,439006.425223,438219.703796,437274.333697,436726.770604,436244.288979,435538.427024,433816.969981
410,275564,Central Park,Denver,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,810438.023097,808244.803889,805155.863258,802598.736735,801195.640708,799657.640124,798600.457230,798423.875011,797461.775214,795133.205809
602,268671,Hampden,Denver,166128.053070,166995.838447,168043.302926,170454.810786,173004.765599,175590.495277,177909.646389,...,525244.032565,523673.717091,522134.523951,521460.718137,521413.062907,521744.191939,522074.783631,522563.712560,522277.831180,520475.767806
681,268662,Five Points,Denver,188674.759005,190474.159808,191852.746828,195655.380983,199917.399170,204490.844183,209338.902439,...,618676.421526,615327.394116,611031.871498,607721.730126,605831.104045,604129.703444,603280.732065,603091.967420,603290.808745,603176.667680

In [6]:
# # Drop Null Values
# denver_real_estate_neighborhood_df = denver_real_estate_neighborhood_df.dropna

In [7]:
#Check Data Types
denver_real_estate_neighborhood_df.dtypes

RegionID          int64
Neighborhood     object
City             object
2000-01-31      float64
2000-02-29      float64
                 ...
2024-10-31      float64
2024-11-30      float64
2024-12-31      float64
2025-01-31      float64
2025-02-28      float64
Length: 305, dtype: object

In [8]:
# Step 1: Melt all date columns (all columns after the first 3)
zillow_melted_df = denver_real_estate_neighborhood_df.melt(
    id_vars=["RegionID", "Neighborhood", "City"],
    var_name="Date",
    value_name="Value"
)

# Step 2: Convert 'Date' to datetime
zillow_melted_df["Date"] = pd.to_datetime(zillow_melted_df["Date"], errors='coerce')

# Step 3: Drop rows where 'Date' couldn't be parsed
zillow_melted_df = zillow_melted_df.dropna(subset=["Date"])

# Step 4: Extract year
zillow_melted_df["Year"] = zillow_melted_df["Date"].dt.year

# Step 5: Group by RegionID, Neighborhood, City, and Year
zillow_grouped_df = zillow_melted_df.groupby(
    ["RegionID", "Neighborhood", "City", "Year"]
)["Value"].mean().round(0).reset_index()

zillow_grouped_df

      RegionID Neighborhood    City  Year     Value
0         6018    Montbello  Denver  2000  134737.0
1         6018    Montbello  Denver  2001  155990.0
2         6018    Montbello  Denver  2002  167373.0
3         6018    Montbello  Denver  2003  169344.0
4         6018    Montbello  Denver  2004  170715.0
...        ...          ...     ...   ...       ...
1971    403518         Cole  Denver  2021  519717.0
1972    403518         Cole  Denver  2022  581639.0
1973    403518         Cole  Denver  2023  568235.0
1974    403518         Cole  Denver  2024  560412.0
1975    403518         Cole  Denver  2025  546799.0

[1976 rows x 5 columns]

In [9]:
#Rename Value(Average) Column
zillow_grouped_df.rename(columns={"Value": "Avg Annual Home Value"},inplace=True)
zillow_grouped_df.head()

   RegionID Neighborhood    City  Year  Avg Annual Home Value
0      6018    Montbello  Denver  2000               134737.0
1      6018    Montbello  Denver  2001               155990.0
2      6018    Montbello  Denver  2002               167373.0
3      6018    Montbello  Denver  2003               169344.0
4      6018    Montbello  Denver  2004               170715.0

In [10]:
#Export CSV
zillow_grouped_df.to_csv("Resources/zillow_yearly.csv")

**Calculate average quarterly home price by neighborhood**

In [11]:
# Step 1: Melt the data
zillow_quarterly_melted_df = denver_real_estate_neighborhood_df.melt(
    id_vars=["RegionID", "Neighborhood", "City"],
    var_name="Date",
    value_name="Value"
)

# Step 2: Convert 'Date' to datetime
zillow_quarterly_melted_df["Date"] = pd.to_datetime(zillow_quarterly_melted_df["Date"], errors='coerce')

# Step 3: Drop invalid dates
zillow_quarterly_melted_df = zillow_quarterly_melted_df.dropna(subset=["Date"])

# Step 4: Extract Year and Quarter
zillow_quarterly_melted_df["Year"] = zillow_quarterly_melted_df["Date"].dt.year
zillow_quarterly_melted_df["Quarter"] = zillow_quarterly_melted_df["Date"].dt.quarter

# Step 5: Group by year and quarter and get average value
grouped_quarterly_df = zillow_quarterly_melted_df.groupby(
    ["RegionID", "Neighborhood", "City", "Year", "Quarter"]
)["Value"].mean().round(2).reset_index()

grouped_quarterly_df

      RegionID Neighborhood    City  Year  Quarter      Value
0         6018    Montbello  Denver  2000        1  127119.42
1         6018    Montbello  Denver  2000        2  131496.90
2         6018    Montbello  Denver  2000        3  137494.02
3         6018    Montbello  Denver  2000        4  142838.48
4         6018    Montbello  Denver  2001        1  148532.88
...        ...          ...     ...   ...      ...        ...
7671    403518         Cole  Denver  2024        1  566195.31
7672    403518         Cole  Denver  2024        2  566684.93
7673    403518         Cole  Denver  2024        3  557518.96
7674    403518         Cole  Denver  2024        4  551247.18
7675    403518         Cole  Denver  2025        1  546798.76

[7676 rows x 6 columns]

In [12]:
grouped_quarterly_df.rename(columns={"Value": "Avg Annual Home Value"},inplace=True)
grouped_quarterly_df.head()

   RegionID Neighborhood    City  Year  Quarter  Avg Annual Home Value
0      6018    Montbello  Denver  2000        1              127119.42
1      6018    Montbello  Denver  2000        2              131496.90
2      6018    Montbello  Denver  2000        3              137494.02
3      6018    Montbello  Denver  2000        4              142838.48
4      6018    Montbello  Denver  2001        1              148532.88

In [13]:
# Export to CSV
grouped_quarterly_df.to_csv("Resources/zillow_quarterly.csv")